apiVersion: v1
kind: Service
metadata:
  name: orchestratepay-backend
  namespace: orchestratepay
  labels:
    app: orchestratepay-backend
spec:
  selector:
    app: orchestratepay-backend
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
